
export const POST_REQUEST="POST_REQUEST";
export const POST_SUCCESS="POST_SUCCESS";
export const POST_ERROR="POST_ERROR";


export const GET_REQUEST="GET_REQUEST";
export const GET_SUCCESS="GET_SUCCESS";
export const GET_ERROR="GET_ERROR";


export const UPDATE_REQUEST="UPDATE_REQUEST";
export const UPDATE_SUCCESS="UPDATE_SUCCESS";
export const UPDATE_ERROR="UPDATE_ERROR";
